---

- hosts: localhost
  pre_tasks:

  tasks:
    - include_role:
        name: base
        apply:
          tags:
            - base
      tags:
        - base
    - include_role:
        name: gui_tools
        apply:
          tags:
            - gui_tools
      tags:
        - gui_tools
    - include_role:
        name: mail
        apply:
          tags:
            - mail
      tags:
        - mail
    - include_role:
        name: editor
        apply:
          tags:
            - editor
      tags:
        - editor
    - include_role:
        name: printer
        apply:
          tags:
            - printer
      tags:
        - printer
